const videos = [
    { titre: "ah cest marrant", fichier: "image/mèmes/vidéos/ah cest marrant.mp4" },
    { titre: "ça va péter", fichier: "image/mèmes/vidéos/ça va péter .mp4" },
    { titre: "c'est honteux", fichier: "image/mèmes/vidéos/c'est honteux.mp4" },
    { titre: "c'est qui a touché a dorian", fichier: "image/mèmes/vidéos/c'est qui a touché a dorian.mp4" },
    { titre: "cest quoi le mot frère", fichier: "image/mèmes/vidéos/cest quoi le mot frère.mp4" },
    { titre: "CHEH - MASKEY", fichier: "image/mèmes/vidéos/CHEH - MASKEY.mp4" },
    { titre: "comment ça mon reuf", fichier: "image/mèmes/vidéos/comment ça mon reuf.mp4" },
    { titre: "en faite non", fichier: "image/mèmes/vidéos/en faite non.mp4" },
    { titre: "encore ça fait beaucoup là non", fichier: "image/mèmes/vidéos/encore ça fait beaucoup là non.mp4" },
    { titre: "imagination", fichier: "image/mèmes/vidéos/imagination.mp4" },
    { titre: "je suis pas venue ici pour souffrir ok", fichier: "image/mèmes/vidéos/je suis pas venue ici pour souffrir ok.mp4" },
    { titre: "le long pavé le pavlar", fichier: "image/mèmes/vidéos/le long pavé le pavlar.mp4" },
    { titre: "oh comme cest bizarre", fichier: "image/mèmes/vidéos/oh comme cest bizarre.mp4" },
    { titre: "shrek aux toilettes", fichier: "image/mèmes/vidéos/shrek aux toilettes.mp4" },
    { titre: "souvenirs denfance", fichier: "image/mèmes/vidéos/souvenirs denfance.mp4" },
    { titre: "arrête de crier", fichier: "image/mèmes/vidéos/arrête de crier .mp4" },
    { titre: "ça y est nous y est", fichier: "image/mèmes/vidéos/ça y est nous y est.mp4" },
    { titre: "canard boit de leau oh no fleefer", fichier: "image/mèmes/vidéos/canard boit de leau oh no fleefer.mp4" },
    { titre: "cest le pire but contre son camp", fichier: "image/mèmes/vidéos/cest le pire but contre son camp.mov" },
    { titre: "chèvre qui crie", fichier: "image/mèmes/vidéos/chèvre qui crie.mp4" },
    { titre: "Galaxy Brain Meme", fichier: "image/mèmes/vidéos/Galaxy Brain Meme.mp4" },
    { titre: "jsuis quun thug mister v parodie lacrim", fichier: "image/mèmes/vidéos/jsuis quun thug mister v parodie lacrim.mp4" },
    { titre: "laisse le jeu kameto", fichier: "image/mèmes/vidéos/laisse le jeu kameto.mp4" },
    { titre: "lebron james", fichier: "image/mèmes/vidéos/lebron james.mp4" },
    { titre: "mais ça va pas ou quoi binobile", fichier: "image/mèmes/vidéos/mais ça va pas ou quoi  binobile.mp4" },
    { titre: "mec qui marche avec musique bizarre", fichier: "image/mèmes/vidéos/mec qui marche avec musique bizarre.mp4" },
    { titre: "message de la france non", fichier: "image/mèmes/vidéos/message de la france non.mp4"},
    { titre: "o. k.", fichier: "image/mèmes/vidéos/o. k..mp4" },
    { titre: "oh putain laurent excuse moi de la réaction laurent baffie", fichier: "image/mèmes/vidéos/oh putain laurent excuse moi de la réaction laurent baffie.mov" },
    { titre: "oh sil vous plaît mon avion", fichier: "image/mèmes/vidéos/oh sil vous plaît mon avion.mp4" },
    { titre: "on est vieux on est aigris on est obèses on sort pas", fichier: "image/mèmes/vidéos/on est vieux on est aigris on est obèses on sort pas.mp4" },
    { titre: "tir raté basket", fichier: "image/mèmes/vidéos/tir raté basket.mp4" }
];
